on:
  push:
    branches:
      - develop
      - master
    paths:
      - 'packages/gfc/**'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install operating system dependencies
        working-directory: ./packages/gfc
        run: npx playwright install-deps
      - name: Run your tests
        working-directory: ./packages/gfc
        run: npm run test:ci
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        working-directory: ./packages/gfc
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: ./coverage/lcov.info
          flags: gfc
          name: codecov-umbrella
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true