name: Tests

on:
  push:
    branches:
      - develop
      - master
    paths:
      - 'packages/gfc/**'
jobs:
  dependencies:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci --workspaces=true
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
  test:
    needs: [dependencies]
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/gfc
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Run tests
        run: npm run test:ci
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./packages/gfc/coverage/lcov.info
          flags: gfc
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true